// Pfade IMMER relativ zu fotoalbum.html
window.LaetitiaFotos = window.LaetitiaFotos || [];
window.LaetitiaFotos.push({
  id:    "sankt_peter_ording_2",
  name:  "Sankt Peter Ording 2",
  fotos: [
    "./alben/sankt Peter Ording 2/1.jpg",
    "./alben/sankt Peter Ording 2/2.jpg",
    "./alben/sankt Peter Ording 2/3.jpg",
    "./alben/sankt Peter Ording 2/4.jpg",
    "./alben/sankt Peter Ording 2/5.jpg",
    "./alben/sankt Peter Ording 2/6.jpg",
    "./alben/sankt Peter Ording 2/7.jpg",
    "./alben/sankt Peter Ording 2/8.jpg",
    "./alben/sankt Peter Ording 2/9.jpg",
    "./alben/sankt Peter Ording 2/10.jpg",
    "./alben/sankt Peter Ording 2/11.jpg",
    "./alben/sankt Peter Ording 2/12.jpg",
    "./alben/sankt Peter Ording 2/13.jpg",
    "./alben/sankt Peter Ording 2/14.jpg",
    "./alben/sankt Peter Ording 2/15.jpg",
    "./alben/sankt Peter Ording 2/16.jpg",
    "./alben/sankt Peter Ording 2/17.jpg",
    "./alben/sankt Peter Ording 2/18.jpg",
    "./alben/sankt Peter Ording 2/19.jpg",
    "./alben/sankt Peter Ording 2/20.jpg",
    "./alben/sankt Peter Ording 2/21.jpg",
    "./alben/sankt Peter Ording 2/22.jpg",
    "./alben/sankt Peter Ording 2/23.jpg",
    "./alben/sankt Peter Ording 2/24.jpg",
    "./alben/sankt Peter Ording 2/25.jpg",
    "./alben/sankt Peter Ording 2/26.jpg",
    "./alben/sankt Peter Ording 2/27.jpg",
    "./alben/sankt Peter Ording 2/28.jpg",
    "./alben/sankt Peter Ording 2/29.jpg",
    "./alben/sankt Peter Ording 2/30.jpg",
    "./alben/sankt Peter Ording 2/31.jpg",
    "./alben/sankt Peter Ording 2/32.jpg",
    "./alben/sankt Peter Ording 2/33.jpg",
    "./alben/sankt Peter Ording 2/34.jpg",
    "./alben/sankt Peter Ording 2/35.jpg",
    "./alben/sankt Peter Ording 2/36.jpg",
    "./alben/sankt Peter Ording 2/37.jpg",
    "./alben/sankt Peter Ording 2/38.jpg",
    "./alben/sankt Peter Ording 2/39.jpg",
    "./alben/sankt Peter Ording 2/40.jpg",
    "./alben/sankt Peter Ording 2/41.jpg",
    "./alben/sankt Peter Ording 2/42.jpg",
    "./alben/sankt Peter Ording 2/43.jpg"
  ]
});
