// Pfade IMMER relativ zu fotoalbum.html
window.LaetitiaFotos = window.LaetitiaFotos || [];
window.LaetitiaFotos.push({
  id:    "sankt_peter_ording_2",
  name:  "Sankt Peter Ording 2",
  fotos: [
    {src:"./alben/sankt Peter Ording 2/1.jpg", text:""},
    {src:"./alben/sankt Peter Ording 2/2.jpg", text:""},
    {src:"./alben/sankt Peter Ording 2/3.jpg", text:""},
    {src:"./alben/sankt Peter Ording 2/4.jpg", text:""},
    {src:"./alben/sankt Peter Ording 2/5.jpg", text:""},
    {src:"./alben/sankt Peter Ording 2/6.jpg", text:""},
    {src:"./alben/sankt Peter Ording 2/7.jpg", text:""},
    {src:"./alben/sankt Peter Ording 2/8.jpg", text:""},
    {src:"./alben/sankt Peter Ording 2/9.jpg", text:""},
    {src:"./alben/sankt Peter Ording 2/10.jpg", text:""},
    {src:"./alben/sankt Peter Ording 2/11.jpg", text:""},
    {src:"./alben/sankt Peter Ording 2/12.jpg", text:""},
    {src:"./alben/sankt Peter Ording 2/13.jpg", text:""},
    {src:"./alben/sankt Peter Ording 2/14.jpg", text:""},
    {src:"./alben/sankt Peter Ording 2/15.jpg", text:""},
    {src:"./alben/sankt Peter Ording 2/16.jpg", text:""},
    {src:"./alben/sankt Peter Ording 2/17.jpg", text:""},
    {src:"./alben/sankt Peter Ording 2/18.jpg", text:""},
    {src:"./alben/sankt Peter Ording 2/19.jpg", text:""},
    {src:"./alben/sankt Peter Ording 2/20.jpg", text:""},
    {src:"./alben/sankt Peter Ording 2/21.jpg", text:""},
    {src:"./alben/sankt Peter Ording 2/22.jpg", text:""},
    {src:"./alben/sankt Peter Ording 2/23.jpg", text:""},
    {src:"./alben/sankt Peter Ording 2/24.jpg", text:""},
    {src:"./alben/sankt Peter Ording 2/25.jpg", text:""},
    {src:"./alben/sankt Peter Ording 2/26.jpg", text:""},
    {src:"./alben/sankt Peter Ording 2/27.jpg", text:""},
    {src:"./alben/sankt Peter Ording 2/28.jpg", text:""},
    {src:"./alben/sankt Peter Ording 2/29.jpg", text:""},
    {src:"./alben/sankt Peter Ording 2/30.jpg", text:""},
    {src:"./alben/sankt Peter Ording 2/31.jpg", text:""},
    {src:"./alben/sankt Peter Ording 2/32.jpg", text:""},
    {src:"./alben/sankt Peter Ording 2/33.jpg", text:""},
    {src:"./alben/sankt Peter Ording 2/34.jpg", text:""},
    {src:"./alben/sankt Peter Ording 2/35.jpg", text:""},
    {src:"./alben/sankt Peter Ording 2/36.jpg", text:""},
    {src:"./alben/sankt Peter Ording 2/37.jpg", text:""},
    {src:"./alben/sankt Peter Ording 2/38.jpg", text:""},
    {src:"./alben/sankt Peter Ording 2/39.jpg", text:""},
    {src:"./alben/sankt Peter Ording 2/40.jpg", text:""},
    {src:"./alben/sankt Peter Ording 2/41.jpg", text:""},
    {src:"./alben/sankt Peter Ording 2/42.jpg", text:""},
    {src:"./alben/sankt Peter Ording 2/43.jpg", text:""}
  ]
});
