// Pfade IMMER relativ zu fotoalbum.html
window.LaetitiaFotos = window.LaetitiaFotos || [];
window.LaetitiaFotos.push({
  id:    "sankt_peter_ording_2",
  name:  "Sankt Peter Ording 2",
  fotos: [
    {src:"./alben/sankt Peter Ording 2/1.jpg", text:"Sommerurlaub in Sankt Peter ording 2025"},
    {src:"./alben/sankt Peter Ording 2/2.jpg", text:"Und wieder haben wir tolles Wetter"},
    {src:"./alben/sankt Peter Ording 2/3.jpg", text:"Einfach nur zum Strand spazieren gehen und die Wellen beobachten"},
    {src:"./alben/sankt Peter Ording 2/4.jpg", text:"Mein Bruder Leonhard ist mitgekommen"},
    {src:"./alben/sankt Peter Ording 2/5.jpg", text:"In diesem umgebauten ehemaligen Bauernhaus haben wir unsere Wohnung"},
    {src:"./alben/sankt Peter Ording 2/6.jpg", text:"Der weiße schöne Strand in Sankt Peter ording"},
    {src:"./alben/sankt Peter Ording 2/7.jpg", text:"Zum Baden ist es noch zu kalt"},
    {src:"./alben/sankt Peter Ording 2/8.jpg", text:"Leonard schiebt mein Rollstuhl durch den tiefen Sand."},
    {src:"./alben/sankt Peter Ording 2/9.jpg", text:"So können wir sehr lange Spaziergänge machen."},
    {src:"./alben/sankt Peter Ording 2/10.jpg", text:"Leonard braucht seine ganze Kraft um mich durch den tiefen Sand Zu schieben."},
    {src:"./alben/sankt Peter Ording 2/11.jpg", text:"Aber das ist für ihn kein Problem."},
    {src:"./alben/sankt Peter Ording 2/12.jpg", text:"Oje, Hilfe! Jetzt wird es ernst."},
    {src:"./alben/sankt Peter Ording 2/13.jpg", text:"Ist das euer Ernst? Bei dem Wetter soll ich ins Wasser?"},
    {src:"./alben/sankt Peter Ording 2/14.jpg", text:"Eine räuberische Möwe"},
    {src:"./alben/sankt Peter Ording 2/15.jpg", text:"Zurück unter dem Pflaumenbaum in unserem Garten"},
    {src:"./alben/sankt Peter Ording 2/16.jpg", text:"Papa hat sich ein Päuschen verdient."},
    {src:"./alben/sankt Peter Ording 2/17.jpg", text:"Stundenlange Abendspaziergänge auf dem Deich mit meinem Bruder."},
    {src:"./alben/sankt Peter Ording 2/18.jpg", text:"Eine sehr ästhetische Landschaft."},
    {src:"./alben/sankt Peter Ording 2/19.jpg", text:"Das ist der Blick vom Deich auf das Meer."},
    {src:"./alben/sankt Peter Ording 2/20.jpg", text:"Wisst ihr warum ich lache? Weil die Mücken noch schneller fliegen als Leonard laufen kann."},
    {src:"./alben/sankt Peter Ording 2/21.jpg", text:"Zwischendurch mal Einblick Auf die Landschaft."},
    {src:"./alben/sankt Peter Ording 2/22.jpg", text:"Lauf mal ein bisschen schneller Bruder! Ich bin schon völlig zerstochen!"},
    {src:"./alben/sankt Peter Ording 2/23.jpg", text:"Bald sind wir wieder zu Hause angekommen! Bald sind wir wieder zu Hause angekommen"},
    {src:"./alben/sankt Peter Ording 2/24.jpg", text:"Das ist unser Haus!"},
    {src:"./alben/sankt Peter Ording 2/25.jpg", text:"Ab und zu weht ein kleines Windchen."},
    {src:"./alben/sankt Peter Ording 2/26.jpg", text:"Eine wunderschöne Heidelandschaft Direkt hinter St Peter ording."},
    {src:"./alben/sankt Peter Ording 2/27.jpg", text:"Mama gefällt es hier sehr. Sie liebt diese Wege direkt durch den Wald hinter den Dünen."},
    {src:"./alben/sankt Peter Ording 2/28.jpg", text:"Ich bin so froh dass Leonard mitgekommen ist."},
    {src:"./alben/sankt Peter Ording 2/29.jpg", text:"Papa braucht ein Päuschen."},
    {src:"./alben/sankt Peter Ording 2/30.jpg", text:"Heute ist es kälter und windiger. Da gibt es keine Mücken die uns ärgern"},
    {src:"./alben/sankt Peter Ording 2/31.jpg", text:"Ich liebe die Sonnenuntergänge über dem Meer."},
    {src:"./alben/sankt Peter Ording 2/32.jpg", text:"So viele Schafe. Ich habe aufgehört zu zählen."},
    {src:"./alben/sankt Peter Ording 2/33.jpg", text:"Und wieder ein wunderschöner Tag am Strand"},
    {src:"./alben/sankt Peter Ording 2/34.jpg", text:"Mein Bruder und mein Papa bei der Arbeit."},
    {src:"./alben/sankt Peter Ording 2/35.jpg", text:"Vor einem bekannten Restaurant am Strand"},
    {src:"./alben/sankt Peter Ording 2/36.jpg", text:"Mama und Leonard Warten Auf die Getränke."},
    {src:"./alben/sankt Peter Ording 2/37.jpg", text:"Genau hier haben wir vor einem Jahr schon mal gesessen."},
    {src:"./alben/sankt Peter Ording 2/38.jpg", text:"Das Wasser sieht sehr einladend aus"},
    {src:"./alben/sankt Peter Ording 2/39.jpg", text:"Ich glaube Papa stürzt sich gleich in die Fluten."},
    {src:"./alben/sankt Peter Ording 2/40.jpg", text:"Spaziergänge sind das schönste hier."},
    {src:"./alben/sankt Peter Ording 2/41.jpg", text:"Mama und ich genießen die Sonne."},
    {src:"./alben/sankt Peter Ording 2/42.jpg", text:"Wie schnell die Zeit vergeht."},
    {src:"./alben/sankt Peter Ording 2/43.jpg", text:"Schon wieder Zeit für Abschiedsfotos."}
  ]
});
