// info.js -- JAguar und NEINguar (Paul Maar)
// Laetitia Lernsystem -- Hoerspiel-Modul
// REGEL 1: kein import(), kein type="module"
// REGEL 4: nur gerade Anfuehrungszeichen

if(!window.LaetitiaHoerspiele) window.LaetitiaHoerspiele = [];

window.LaetitiaHoerspiele.push({
  id: "jaguar-und-neinguar",
  titel: "JAguar und NEINguar",
  untertitel: "Paul Maar",
  cover: "./buecher/JAguar und NEINguar/JaguarundNeinguar.jpg",
  kapitel: [
    { nr:  1, titel: "[Ansage]",                                    datei: "./buecher/JAguar und NEINguar/01 [Ansage].m4a" },
    { nr:  2, titel: "Verwurmter Apfel",                            datei: "./buecher/JAguar und NEINguar/02 Verwurmter Apfel.m4a" },
    { nr:  3, titel: "Herr Lehmann und Herr Diepenkoetter",         datei: "./buecher/JAguar und NEINguar/03 Herr Lehmann und Herr Diepenkotte.m4a" },
    { nr:  4, titel: "Die gewohnten Dinge",                         datei: "./buecher/JAguar und NEINguar/04 Die gewohnten Dinge.m4a" },
    { nr:  5, titel: "Das Dingsda",                                 datei: "./buecher/JAguar und NEINguar/05 Das Dingsda.m4a" },
    { nr:  6, titel: "Raetsel 1 (Deine Hosen)",                     datei: "./buecher/JAguar und NEINguar/06 Ratsel 1 (Deine Hosen).m4a" },
    { nr:  7, titel: "Die einfachen Woerter",                       datei: "./buecher/JAguar und NEINguar/07 Die einfachen Worter.m4a" },
    { nr:  8, titel: "Vergangenheit - Gegenwart - Zukunft",         datei: "./buecher/JAguar und NEINguar/08 Vergangenheit - Gegenwart - Zukun.m4a" },
    { nr:  9, titel: "Raetsel 2 (Alt)",                             datei: "./buecher/JAguar und NEINguar/09 Ratsel 2 (Alt).m4a" },
    { nr: 10, titel: "Urlaub",                                      datei: "./buecher/JAguar und NEINguar/10 Urlaub.m4a" },
    { nr: 11, titel: "Feuerdrachen",                                datei: "./buecher/JAguar und NEINguar/11 Feuerdrachen.m4a" },
    { nr: 12, titel: "Drachen bei Regen",                           datei: "./buecher/JAguar und NEINguar/12 Drachen bei Regen.m4a" },
    { nr: 13, titel: "Ein Irrtum",                                  datei: "./buecher/JAguar und NEINguar/13 Ein Irrtum.m4a" },
    { nr: 14, titel: "Raetsel 3 (Die Nase)",                        datei: "./buecher/JAguar und NEINguar/14 Ratsel 3 (Die Nase).m4a" },
    { nr: 15, titel: "Der Unterschied",                             datei: "./buecher/JAguar und NEINguar/15 Der Unterschied.m4a" },
    { nr: 16, titel: "Jaguar und Neinguar",                         datei: "./buecher/JAguar und NEINguar/16 Jaguar und Neinguar.m4a" },
    { nr: 17, titel: "Das Faultier",                                datei: "./buecher/JAguar und NEINguar/17 Das faultier.m4a" },
    { nr: 18, titel: "Tier-Lieben",                                 datei: "./buecher/JAguar und NEINguar/18 Tier-Lieben.m4a" },
    { nr: 19, titel: "Kluge Katze",                                 datei: "./buecher/JAguar und NEINguar/19 Kluge Katze.m4a" },
    { nr: 20, titel: "Raetsel 4 (Das Wollknauel)",                  datei: "./buecher/JAguar und NEINguar/20 Ratsel 4 (Das Wollknauel).m4a" },
    { nr: 21, titel: "Feuersalamander",                             datei: "./buecher/JAguar und NEINguar/21 Feuersalamander.m4a" },
    { nr: 22, titel: "Tier und Sport - Ein leidiges Kapitel",       datei: "./buecher/JAguar und NEINguar/22 Tier und Sport - Ein leidiges Kap.m4a" },
    { nr: 23, titel: "Irgendwo in der Welt",                        datei: "./buecher/JAguar und NEINguar/23 Irgendwo in der Welt.m4a" },
    { nr: 24, titel: "Ohne Zweifel",                                datei: "./buecher/JAguar und NEINguar/24 Ohne Zweifel.m4a" },
    { nr: 25, titel: "Raetsel 5 (Die Kirsche)",                     datei: "./buecher/JAguar und NEINguar/25 Ratsel 5 (Die Kirsche).m4a" },
    { nr: 26, titel: "Alles vom Aal",                               datei: "./buecher/JAguar und NEINguar/26 Alles vom Aal.m4a" },
    { nr: 27, titel: "Das Sams - Wann kommt es?",                   datei: "./buecher/JAguar und NEINguar/27 Das Sams - Wann kommt es.m4a" },
    { nr: 28, titel: "Tier-Zwei=Zeiler (1)",                        datei: "./buecher/JAguar und NEINguar/28 Tier-Zwei=Zeiler (1).m4a" },
    { nr: 29, titel: "Raetsel 6 (Deine Schuhe)",                    datei: "./buecher/JAguar und NEINguar/29 Ratsel 6 (Deine Schuhe).m4a" },
    { nr: 30, titel: "Kuessen",                                     datei: "./buecher/JAguar und NEINguar/30 Kuessen.m4a" },
    { nr: 31, titel: "Im Bett",                                     datei: "./buecher/JAguar und NEINguar/31 Im Bett.m4a" },
    { nr: 32, titel: "Naechtlicher Besuch",                         datei: "./buecher/JAguar und NEINguar/32 Nachtlicher Besuch.m4a" },
    { nr: 33, titel: "Ganz leise...",                               datei: "./buecher/JAguar und NEINguar/33 Ganz leise....m4a" },
    { nr: 34, titel: "Ein Zirkusabenteuer mit einem Loewe und viel...", datei: "./buecher/JAguar und NEINguar/34 Ein Zirkusabenteuer mit einem Low.m4a" },
    { nr: 35, titel: "Abzaehlreim 1",                               datei: "./buecher/JAguar und NEINguar/35 Abzahlreim 1.m4a" },
    { nr: 36, titel: "Abzaehlreim 2",                               datei: "./buecher/JAguar und NEINguar/36 Abzahlreim 2.m4a" },
    { nr: 37, titel: "Der Buchstabe Z",                             datei: "./buecher/JAguar und NEINguar/37 Der Buchstabe Z.m4a" },
    { nr: 38, titel: "Raetsel 7 (Die Fingerhandschuhe)",            datei: "./buecher/JAguar und NEINguar/38 Ratsel 7 (Die Fingerhandschuhe).m4a" },
    { nr: 39, titel: "A - E - I - O - U",                           datei: "./buecher/JAguar und NEINguar/39 A - E - I - O - U.m4a" },
    { nr: 40, titel: "Matzki",                                      datei: "./buecher/JAguar und NEINguar/40 Matzki.m4a" },
    { nr: 41, titel: "Noten, Noten...",                             datei: "./buecher/JAguar und NEINguar/41 Noten, Noten....m4a" },
    { nr: 42, titel: "Hier stimmt was nicht!",                      datei: "./buecher/JAguar und NEINguar/42 Hier stimmt was nicht!.m4a" },
    { nr: 43, titel: "Tier-Zwei=Zeiler (2)",                        datei: "./buecher/JAguar und NEINguar/43 Tier-Zwei=Zeiler (2).m4a" },
    { nr: 44, titel: "Raetsel 8 (Der Weg)",                         datei: "./buecher/JAguar und NEINguar/44 Ratsel 8 (Der Weg).m4a" },
    { nr: 45, titel: "Bekanntschaft",                               datei: "./buecher/JAguar und NEINguar/45 Bekanntschaft.m4a" },
    { nr: 46, titel: "Land auf dem Sonntag",                        datei: "./buecher/JAguar und NEINguar/46 Land auf dem Sonntag.m4a" },
    { nr: 47, titel: "Spar ohne Schwein",                           datei: "./buecher/JAguar und NEINguar/47 Spar ohne Schwein.m4a" },
    { nr: 48, titel: "Raetsel 9 (Die Hand)",                        datei: "./buecher/JAguar und NEINguar/48 Ratsel 9 (Die Hand).m4a" },
    { nr: 49, titel: "Walli und Horsti",                            datei: "./buecher/JAguar und NEINguar/49 Walli und Horsti.m4a" },
    { nr: 50, titel: "Halb so schlimm!",                            datei: "./buecher/JAguar und NEINguar/50 Halb so schlimm!.m4a" },
    { nr: 51, titel: "Raetsel 10 (Das Chamaeleon)",                 datei: "./buecher/JAguar und NEINguar/51 Ratsel 10 (Das Chamaleon).m4a" },
    { nr: 52, titel: "Wie man sich als Erwachsener fuehlt",         datei: "./buecher/JAguar und NEINguar/52 Wie man sich als Erwachsener fuhl.m4a" },
    { nr: 53, titel: "Zukunft",                                     datei: "./buecher/JAguar und NEINguar/53 Zukunft.m4a" },
    { nr: 54, titel: "In hundert Jahren",                           datei: "./buecher/JAguar und NEINguar/54 In hundert Jahren.m4a" }
  ]
});
