// schule_mathe_data.js
// Aufgaben aus "Nase vorn! Rechnen bis 20" (Cornelsen, Klasse 1)
// Stufen SMA1–SMA6 als 4-Antworten-Aufgaben

(function(){
"use strict";

var aufgaben = [

  // ── SMA1: Rechnen mit der 10 (Plus) — Seite 7 ──────────────────────────────
  { heft:"nasevorn", seite:7, typ:"mathe", stufe:"SMA1",
    text:"10 + 2 = ?", frage:"Was ist das Ergebnis?",
    antwort_a:"11", antwort_b:"12", antwort_c:"13", antwort_d:"20",
    richtig:"B", erklaerung:"10 + 2 = 12" },
  { heft:"nasevorn", seite:7, typ:"mathe", stufe:"SMA1",
    text:"10 + 5 = ?", frage:"Was ist das Ergebnis?",
    antwort_a:"14", antwort_b:"16", antwort_c:"15", antwort_d:"50",
    richtig:"C", erklaerung:"10 + 5 = 15" },
  { heft:"nasevorn", seite:7, typ:"mathe", stufe:"SMA1",
    text:"10 + 8 = ?", frage:"Was ist das Ergebnis?",
    antwort_a:"17", antwort_b:"18", antwort_c:"19", antwort_d:"80",
    richtig:"B", erklaerung:"10 + 8 = 18" },
  { heft:"nasevorn", seite:7, typ:"mathe", stufe:"SMA1",
    text:"10 + 1 = ?", frage:"Was ist das Ergebnis?",
    antwort_a:"10", antwort_b:"12", antwort_c:"11", antwort_d:"101",
    richtig:"C", erklaerung:"10 + 1 = 11" },
  { heft:"nasevorn", seite:7, typ:"mathe", stufe:"SMA1",
    text:"10 + 4 = ?", frage:"Was ist das Ergebnis?",
    antwort_a:"14", antwort_b:"13", antwort_c:"15", antwort_d:"40",
    richtig:"A", erklaerung:"10 + 4 = 14" },
  { heft:"nasevorn", seite:7, typ:"mathe", stufe:"SMA1",
    text:"7 + 10 = ?", frage:"Was ist das Ergebnis?",
    antwort_a:"16", antwort_b:"18", antwort_c:"17", antwort_d:"70",
    richtig:"C", erklaerung:"7 + 10 = 17. Die Reihenfolge ist egal!" },
  { heft:"nasevorn", seite:7, typ:"mathe", stufe:"SMA1",
    text:"3 + 10 = ?", frage:"Was ist das Ergebnis?",
    antwort_a:"13", antwort_b:"30", antwort_c:"12", antwort_d:"14",
    richtig:"A", erklaerung:"3 + 10 = 13" },
  { heft:"nasevorn", seite:7, typ:"mathe", stufe:"SMA1",
    text:"9 + 10 = ?", frage:"Was ist das Ergebnis?",
    antwort_a:"18", antwort_b:"20", antwort_c:"19", antwort_d:"90",
    richtig:"C", erklaerung:"9 + 10 = 19" },
  { heft:"nasevorn", seite:7, typ:"mathe", stufe:"SMA1",
    text:"13 = 10 + ?", frage:"Welche Zahl fehlt?",
    antwort_a:"2", antwort_b:"3", antwort_c:"4", antwort_d:"30",
    richtig:"B", erklaerung:"10 + 3 = 13, also fehlt die 3." },
  { heft:"nasevorn", seite:7, typ:"mathe", stufe:"SMA1",
    text:"17 = 10 + ?", frage:"Welche Zahl fehlt?",
    antwort_a:"6", antwort_b:"8", antwort_c:"7", antwort_d:"70",
    richtig:"C", erklaerung:"10 + 7 = 17, also fehlt die 7." },
  { heft:"nasevorn", seite:7, typ:"mathe", stufe:"SMA1",
    text:"20 = 10 + ?", frage:"Welche Zahl fehlt?",
    antwort_a:"10", antwort_b:"0", antwort_c:"20", antwort_d:"12",
    richtig:"A", erklaerung:"10 + 10 = 20" },

  // ── SMA1: Rechnen mit der 10 (Minus) — Seite 23 ────────────────────────────
  { heft:"nasevorn", seite:23, typ:"mathe", stufe:"SMA1",
    text:"13 - 3 = ?", frage:"Was ist das Ergebnis?",
    antwort_a:"9", antwort_b:"10", antwort_c:"11", antwort_d:"16",
    richtig:"B", erklaerung:"13 - 3 = 10. Wir nehmen die Einer weg." },
  { heft:"nasevorn", seite:23, typ:"mathe", stufe:"SMA1",
    text:"16 - 6 = ?", frage:"Was ist das Ergebnis?",
    antwort_a:"10", antwort_b:"9", antwort_c:"11", antwort_d:"12",
    richtig:"A", erklaerung:"16 - 6 = 10" },
  { heft:"nasevorn", seite:23, typ:"mathe", stufe:"SMA1",
    text:"14 - 10 = ?", frage:"Was ist das Ergebnis?",
    antwort_a:"3", antwort_b:"5", antwort_c:"4", antwort_d:"24",
    richtig:"C", erklaerung:"14 - 10 = 4. Die 10 wegnehmen, die 4 bleibt." },
  { heft:"nasevorn", seite:23, typ:"mathe", stufe:"SMA1",
    text:"19 - 10 = ?", frage:"Was ist das Ergebnis?",
    antwort_a:"8", antwort_b:"9", antwort_c:"10", antwort_d:"29",
    richtig:"B", erklaerung:"19 - 10 = 9" },
  { heft:"nasevorn", seite:23, typ:"mathe", stufe:"SMA1",
    text:"20 - 10 = ?", frage:"Was ist das Ergebnis?",
    antwort_a:"0", antwort_b:"10", antwort_c:"20", antwort_d:"12",
    richtig:"B", erklaerung:"20 - 10 = 10" },

  // ── SMA2: Grosse und kleine Aufgaben — Seiten 8 + 24 ───────────────────────
  { heft:"nasevorn", seite:8, typ:"mathe", stufe:"SMA2",
    text:"Die kleine Aufgabe von 14 + 5 ist...",
    frage:"Welche Aufgabe hilft?",
    antwort_a:"10 + 5", antwort_b:"4 + 5", antwort_c:"14 + 10", antwort_d:"1 + 5",
    richtig:"B", erklaerung:"4 + 5 = 9, also ist 14 + 5 = 19. Die kleine Aufgabe hilft!" },
  { heft:"nasevorn", seite:8, typ:"mathe", stufe:"SMA2",
    text:"14 + 5 = ?", frage:"Was ist das Ergebnis?",
    antwort_a:"18", antwort_b:"20", antwort_c:"19", antwort_d:"9",
    richtig:"C", erklaerung:"14 + 5 = 19. Tipp: 4 + 5 = 9, also 14 + 5 = 19" },
  { heft:"nasevorn", seite:8, typ:"mathe", stufe:"SMA2",
    text:"12 + 6 = ?", frage:"Was ist das Ergebnis?",
    antwort_a:"17", antwort_b:"18", antwort_c:"16", antwort_d:"8",
    richtig:"B", erklaerung:"12 + 6 = 18. Tipp: 2 + 6 = 8, also 12 + 6 = 18" },
  { heft:"nasevorn", seite:8, typ:"mathe", stufe:"SMA2",
    text:"15 + 1 = ?", frage:"Was ist das Ergebnis?",
    antwort_a:"14", antwort_b:"17", antwort_c:"16", antwort_d:"6",
    richtig:"C", erklaerung:"15 + 1 = 16. Eins weiter zählen!" },
  { heft:"nasevorn", seite:8, typ:"mathe", stufe:"SMA2",
    text:"17 + 3 = ?", frage:"Was ist das Ergebnis?",
    antwort_a:"20", antwort_b:"19", antwort_c:"21", antwort_d:"10",
    richtig:"A", erklaerung:"17 + 3 = 20. Tipp: 7 + 3 = 10, also 17 + 3 = 20" },

  // ── SMA3: Verdoppeln — Seite 13 ────────────────────────────────────────────
  { heft:"nasevorn", seite:13, typ:"mathe", stufe:"SMA3",
    text:"Das Doppelte von 1 ist...", frage:"Was ist 1 + 1?",
    antwort_a:"1", antwort_b:"2", antwort_c:"3", antwort_d:"11",
    richtig:"B", erklaerung:"1 + 1 = 2. Das Doppelte von 1 ist 2." },
  { heft:"nasevorn", seite:13, typ:"mathe", stufe:"SMA3",
    text:"Das Doppelte von 3 ist...", frage:"Was ist 3 + 3?",
    antwort_a:"5", antwort_b:"9", antwort_c:"6", antwort_d:"33",
    richtig:"C", erklaerung:"3 + 3 = 6. Das Doppelte von 3 ist 6." },
  { heft:"nasevorn", seite:13, typ:"mathe", stufe:"SMA3",
    text:"Das Doppelte von 5 ist...", frage:"Was ist 5 + 5?",
    antwort_a:"10", antwort_b:"8", antwort_c:"55", antwort_d:"12",
    richtig:"A", erklaerung:"5 + 5 = 10. Das Doppelte von 5 ist 10." },
  { heft:"nasevorn", seite:13, typ:"mathe", stufe:"SMA3",
    text:"Das Doppelte von 7 ist...", frage:"Was ist 7 + 7?",
    antwort_a:"13", antwort_b:"14", antwort_c:"12", antwort_d:"77",
    richtig:"B", erklaerung:"7 + 7 = 14. Das Doppelte von 7 ist 14." },
  { heft:"nasevorn", seite:13, typ:"mathe", stufe:"SMA3",
    text:"Das Doppelte von 9 ist...", frage:"Was ist 9 + 9?",
    antwort_a:"18", antwort_b:"17", antwort_c:"20", antwort_d:"99",
    richtig:"A", erklaerung:"9 + 9 = 18. Das Doppelte von 9 ist 18." },
  { heft:"nasevorn", seite:13, typ:"mathe", stufe:"SMA3",
    text:"Das Doppelte von 10 ist...", frage:"Was ist 10 + 10?",
    antwort_a:"11", antwort_b:"100", antwort_c:"20", antwort_d:"19",
    richtig:"C", erklaerung:"10 + 10 = 20." },

  // ── SMA3: Halbieren — Seite 15 ─────────────────────────────────────────────
  { heft:"nasevorn", seite:15, typ:"mathe", stufe:"SMA3",
    text:"Die Haelfte von 2 ist...", frage:"Was ist die Haelfte von 2?",
    antwort_a:"1", antwort_b:"2", antwort_c:"4", antwort_d:"0",
    richtig:"A", erklaerung:"2 = 1 + 1. Die Haelfte von 2 ist 1." },
  { heft:"nasevorn", seite:15, typ:"mathe", stufe:"SMA3",
    text:"Die Haelfte von 6 ist...", frage:"Was ist die Haelfte von 6?",
    antwort_a:"2", antwort_b:"4", antwort_c:"3", antwort_d:"12",
    richtig:"C", erklaerung:"6 = 3 + 3. Die Haelfte von 6 ist 3." },
  { heft:"nasevorn", seite:15, typ:"mathe", stufe:"SMA3",
    text:"Die Haelfte von 10 ist...", frage:"Was ist die Haelfte von 10?",
    antwort_a:"5", antwort_b:"4", antwort_c:"6", antwort_d:"20",
    richtig:"A", erklaerung:"10 = 5 + 5. Die Haelfte von 10 ist 5." },
  { heft:"nasevorn", seite:15, typ:"mathe", stufe:"SMA3",
    text:"Die Haelfte von 14 ist...", frage:"Was ist die Haelfte von 14?",
    antwort_a:"8", antwort_b:"6", antwort_c:"7", antwort_d:"28",
    richtig:"C", erklaerung:"14 = 7 + 7. Die Haelfte von 14 ist 7." },
  { heft:"nasevorn", seite:15, typ:"mathe", stufe:"SMA3",
    text:"Die Haelfte von 20 ist...", frage:"Was ist die Haelfte von 20?",
    antwort_a:"10", antwort_b:"5", antwort_c:"15", antwort_d:"40",
    richtig:"A", erklaerung:"20 = 10 + 10. Die Haelfte von 20 ist 10." },

  // ── SMA4: Fast verdoppeln — Seite 14 ───────────────────────────────────────
  { heft:"nasevorn", seite:14, typ:"mathe", stufe:"SMA4",
    text:"5 + 6 = ? (Tipp: 5 + 5 + 1)", frage:"Was ist das Ergebnis?",
    antwort_a:"10", antwort_b:"12", antwort_c:"11", antwort_d:"9",
    richtig:"C", erklaerung:"5 + 6 = 11. Tipp: fast verdoppeln: 5 + 5 = 10, dann noch + 1 = 11" },
  { heft:"nasevorn", seite:14, typ:"mathe", stufe:"SMA4",
    text:"7 + 8 = ? (Tipp: 7 + 7 + 1)", frage:"Was ist das Ergebnis?",
    antwort_a:"14", antwort_b:"16", antwort_c:"15", antwort_d:"13",
    richtig:"C", erklaerung:"7 + 8 = 15. Tipp: 7 + 7 = 14, dann + 1 = 15" },
  { heft:"nasevorn", seite:14, typ:"mathe", stufe:"SMA4",
    text:"8 + 9 = ? (Tipp: 8 + 8 + 1)", frage:"Was ist das Ergebnis?",
    antwort_a:"16", antwort_b:"18", antwort_c:"17", antwort_d:"15",
    richtig:"C", erklaerung:"8 + 9 = 17. Tipp: 8 + 8 = 16, dann + 1 = 17" },
  { heft:"nasevorn", seite:14, typ:"mathe", stufe:"SMA4",
    text:"6 + 7 = ? (Tipp: 6 + 6 + 1)", frage:"Was ist das Ergebnis?",
    antwort_a:"14", antwort_b:"12", antwort_c:"13", antwort_d:"11",
    richtig:"C", erklaerung:"6 + 7 = 13. Tipp: 6 + 6 = 12, dann + 1 = 13" },
  { heft:"nasevorn", seite:14, typ:"mathe", stufe:"SMA4",
    text:"9 + 10 = ?", frage:"Was ist das Ergebnis?",
    antwort_a:"18", antwort_b:"20", antwort_c:"19", antwort_d:"17",
    richtig:"C", erklaerung:"9 + 10 = 19. Tipp: 9 + 9 = 18, dann + 1 = 19" },

  // ── SMA5: Tauschaufgaben — Seiten 9 + 16 ───────────────────────────────────
  { heft:"nasevorn", seite:9, typ:"mathe", stufe:"SMA5",
    text:"3 + 12 = 15. Was ist die Tauschaufgabe?",
    frage:"Welche Aufgabe hat das gleiche Ergebnis?",
    antwort_a:"12 - 3", antwort_b:"12 + 3", antwort_c:"15 - 3", antwort_d:"3 - 12",
    richtig:"B", erklaerung:"12 + 3 = 15. Wir tauschen die Zahlen — das Ergebnis bleibt gleich!" },
  { heft:"nasevorn", seite:9, typ:"mathe", stufe:"SMA5",
    text:"6 + 11 = ?", frage:"Was ist das Ergebnis?",
    antwort_a:"16", antwort_b:"18", antwort_c:"17", antwort_d:"56",
    richtig:"C", erklaerung:"6 + 11 = 17. Tauschaufgabe: 11 + 6 = 17 auch!" },
  { heft:"nasevorn", seite:9, typ:"mathe", stufe:"SMA5",
    text:"4 + 14 = ?", frage:"Was ist das Ergebnis?",
    antwort_a:"17", antwort_b:"19", antwort_c:"18", antwort_d:"44",
    richtig:"C", erklaerung:"4 + 14 = 18. Tauschaufgabe: 14 + 4 = 18 auch!" },
  { heft:"nasevorn", seite:16, typ:"mathe", stufe:"SMA5",
    text:"4 + 7 = 11. Was ist die Tauschaufgabe?",
    frage:"Welche Aufgabe ergibt auch 11?",
    antwort_a:"7 - 4", antwort_b:"11 - 7", antwort_c:"7 + 4", antwort_d:"4 + 11",
    richtig:"C", erklaerung:"7 + 4 = 11. Zahlen tauschen — Ergebnis bleibt 11!" },
  { heft:"nasevorn", seite:16, typ:"mathe", stufe:"SMA5",
    text:"6 + 8 = ?", frage:"Was ist das Ergebnis?",
    antwort_a:"13", antwort_b:"14", antwort_c:"15", antwort_d:"68",
    richtig:"B", erklaerung:"6 + 8 = 14. Und: 8 + 6 = 14 ebenfalls!" },

  // ── SMA6: Plus 9 und Plus 11 — Seiten 12 + 28 ──────────────────────────────
  { heft:"nasevorn", seite:12, typ:"mathe", stufe:"SMA6",
    text:"6 + 9 = ? (Tipp: 6 + 10 - 1)", frage:"Was ist das Ergebnis?",
    antwort_a:"14", antwort_b:"16", antwort_c:"15", antwort_d:"69",
    richtig:"C", erklaerung:"6 + 9 = 15. Trick: erst +10 dann -1: 6+10=16, dann 16-1=15" },
  { heft:"nasevorn", seite:12, typ:"mathe", stufe:"SMA6",
    text:"3 + 9 = ? (Tipp: 3 + 10 - 1)", frage:"Was ist das Ergebnis?",
    antwort_a:"13", antwort_b:"11", antwort_c:"12", antwort_d:"39",
    richtig:"C", erklaerung:"3 + 9 = 12. Trick: 3+10=13, dann 13-1=12" },
  { heft:"nasevorn", seite:12, typ:"mathe", stufe:"SMA6",
    text:"8 + 9 = ? (Tipp: 8 + 10 - 1)", frage:"Was ist das Ergebnis?",
    antwort_a:"17", antwort_b:"18", antwort_c:"16", antwort_d:"89",
    richtig:"A", erklaerung:"8 + 9 = 17. Trick: 8+10=18, dann 18-1=17" },
  { heft:"nasevorn", seite:12, typ:"mathe", stufe:"SMA6",
    text:"2 + 11 = ? (Tipp: 2 + 10 + 1)", frage:"Was ist das Ergebnis?",
    antwort_a:"14", antwort_b:"12", antwort_c:"13", antwort_d:"21",
    richtig:"C", erklaerung:"2 + 11 = 13. Trick: erst +10 dann +1: 2+10=12, dann 12+1=13" },
  { heft:"nasevorn", seite:12, typ:"mathe", stufe:"SMA6",
    text:"5 + 11 = ? (Tipp: 5 + 10 + 1)", frage:"Was ist das Ergebnis?",
    antwort_a:"15", antwort_b:"17", antwort_c:"16", antwort_d:"51",
    richtig:"C", erklaerung:"5 + 11 = 16. Trick: 5+10=15, dann 15+1=16" },
  { heft:"nasevorn", seite:12, typ:"mathe", stufe:"SMA6",
    text:"7 + 11 = ? (Tipp: 7 + 10 + 1)", frage:"Was ist das Ergebnis?",
    antwort_a:"17", antwort_b:"19", antwort_c:"18", antwort_d:"71",
    richtig:"C", erklaerung:"7 + 11 = 18. Trick: 7+10=17, dann 17+1=18" },

  // ── SMA6: Minus 9 und Minus 11 — Seite 28 ──────────────────────────────────
  { heft:"nasevorn", seite:28, typ:"mathe", stufe:"SMA6",
    text:"12 - 9 = ? (Tipp: 12 - 10 + 1)", frage:"Was ist das Ergebnis?",
    antwort_a:"2", antwort_b:"4", antwort_c:"3", antwort_d:"21",
    richtig:"C", erklaerung:"12 - 9 = 3. Trick: 12-10=2, dann 2+1=3" },
  { heft:"nasevorn", seite:28, typ:"mathe", stufe:"SMA6",
    text:"15 - 9 = ? (Tipp: 15 - 10 + 1)", frage:"Was ist das Ergebnis?",
    antwort_a:"5", antwort_b:"7", antwort_c:"6", antwort_d:"4",
    richtig:"C", erklaerung:"15 - 9 = 6. Trick: 15-10=5, dann 5+1=6" },
  { heft:"nasevorn", seite:28, typ:"mathe", stufe:"SMA6",
    text:"14 - 11 = ? (Tipp: 14 - 10 - 1)", frage:"Was ist das Ergebnis?",
    antwort_a:"4", antwort_b:"2", antwort_c:"5", antwort_d:"3",
    richtig:"D", erklaerung:"14 - 11 = 3. Trick: 14-10=4, dann 4-1=3" },
  { heft:"nasevorn", seite:28, typ:"mathe", stufe:"SMA6",
    text:"19 - 11 = ? (Tipp: 19 - 10 - 1)", frage:"Was ist das Ergebnis?",
    antwort_a:"9", antwort_b:"7", antwort_c:"10", antwort_d:"8",
    richtig:"D", erklaerung:"19 - 11 = 8. Trick: 19-10=9, dann 9-1=8" }

];

(function(){
  var api = window.LaetitiaDataRegistryApi;
  if(api && typeof api.get === "function"){
    var existing = api.get("schule_mathe") || [];
    api.set("schule_mathe", existing.filter(function(t){
      return t.heft !== "nasevorn";
    }).concat(aufgaben));
  } else {
    window.LaetitiaSchuleMatheAufgaben = aufgaben;
  }
})();

})();
