// info.js -- Das Fliegende Kamel (Nasreddin Hodscha)
// Laetitia Lernsystem -- Hoerspiel-Modul
// REGEL 1: kein import(), kein type="module"
// REGEL 4: nur gerade Anfuehrungszeichen

if(!window.LaetitiaHoerspiele) window.LaetitiaHoerspiele = [];

window.LaetitiaHoerspiele.push({
  id: "das-fliegende-kamel",
  titel: "Das Fliegende Kamel",
  untertitel: "Nasreddin Hodscha",
  cover: "./buecher/Das Fliegende Kamel/DasfliegendeKamel.jpg",
  kapitel: [
    { nr:  1, titel: "Nasreddin Hodscha",                     datei: "./buecher/Das Fliegende Kamel/1-01 Nasreddin Hodscha.m4a" },
    { nr:  2, titel: "Der Klang Des Geldes",                  datei: "./buecher/Das Fliegende Kamel/1-02 Der Klang Des Geldes.m4a" },
    { nr:  3, titel: "Der Langschlafer",                      datei: "./buecher/Das Fliegende Kamel/1-03 Der Langschlafer.m4a" },
    { nr:  4, titel: "Gerechtes Urteil",                      datei: "./buecher/Das Fliegende Kamel/1-04 Gerechtes Urteil.m4a" },
    { nr:  5, titel: "Nuesse Und Melonen",                    datei: "./buecher/Das Fliegende Kamel/1-05 Nusse Und Melonen.m4a" },
    { nr:  6, titel: "Der Gar Nicht Narrische Narr",          datei: "./buecher/Das Fliegende Kamel/1-06 Der Gar Nicht Narrische Narr.m4a" },
    { nr:  7, titel: "Die Predigt",                           datei: "./buecher/Das Fliegende Kamel/1-07 Die Predigt.m4a" },
    { nr:  8, titel: "Das Fliegende Kamel",                   datei: "./buecher/Das Fliegende Kamel/1-08 Das Fliegende Kamel.m4a" },
    { nr:  9, titel: "Glueckliche Rettung Eines Ertrinkenden",datei: "./buecher/Das Fliegende Kamel/1-09 Gluckliche Rettung Eines Ertrin.m4a" },
    { nr: 10, titel: "Nasreddins Weiser Rat",                 datei: "./buecher/Das Fliegende Kamel/1-10 Nasreddins Weiser Rat.m4a" },
    { nr: 11, titel: "Der Esel",                              datei: "./buecher/Das Fliegende Kamel/1-11 Der Esel.m4a" },
    { nr: 12, titel: "Die Huehnersuppe",                      datei: "./buecher/Das Fliegende Kamel/1-12 Die Huhnersuppe.m4a" },
    { nr: 13, titel: "Der Teure Schneider",                   datei: "./buecher/Das Fliegende Kamel/1-13 Der Teure Schneider.m4a" },
    { nr: 14, titel: "Der Bogenschuetze",                     datei: "./buecher/Das Fliegende Kamel/1-14 Der Bogenschutze.m4a" },
    { nr: 15, titel: "Am Fluss",                              datei: "./buecher/Das Fliegende Kamel/1-15 Am Fluss.m4a" },
    { nr: 16, titel: "Das Gerechte Urteil",                   datei: "./buecher/Das Fliegende Kamel/1-16 Das Gerechte Urteil.m4a" },
    { nr: 17, titel: "Nasreddin Wettet",                      datei: "./buecher/Das Fliegende Kamel/1-17 Nasreddin Wettet.m4a" },
    { nr: 18, titel: "Die Hungrige Tasche",                   datei: "./buecher/Das Fliegende Kamel/1-18 Die Hungrige Tasche.m4a" },
    { nr: 19, titel: "Das Telefon",                           datei: "./buecher/Das Fliegende Kamel/1-19 Das Telefon.m4a" },
    { nr: 20, titel: "Der Wetterbericht",                     datei: "./buecher/Das Fliegende Kamel/1-20 Der Wetterbericht.m4a" },
    { nr: 21, titel: "Im Auto",                               datei: "./buecher/Das Fliegende Kamel/1-21 Im Auto.m4a" },
    { nr: 22, titel: "Der Brief",                             datei: "./buecher/Das Fliegende Kamel/1-22 Der Brief.m4a" },
    { nr: 23, titel: "Die Gans",                              datei: "./buecher/Das Fliegende Kamel/1-23 Die Gans.m4a" },
    { nr: 24, titel: "Regen",                                 datei: "./buecher/Das Fliegende Kamel/1-24 Regen.m4a" },
    { nr: 25, titel: "Schlafprobleme",                        datei: "./buecher/Das Fliegende Kamel/1-25 Schlafprobleme.m4a" },
    { nr: 26, titel: "Die Kaelte",                            datei: "./buecher/Das Fliegende Kamel/1-26 Die Kalte.m4a" },
    { nr: 27, titel: "Eine Diaet",                            datei: "./buecher/Das Fliegende Kamel/1-27 Eine Diat.m4a" },
    { nr: 28, titel: "Die Beiden Glaeser",                    datei: "./buecher/Das Fliegende Kamel/1-28 Die Beiden Glaser.m4a" },
    { nr: 29, titel: "Hohes Alter",                           datei: "./buecher/Das Fliegende Kamel/1-29 Hohes Alter.m4a" },
    { nr: 30, titel: "Nasreddin Hodscha (CD 1 Ende)",         datei: "./buecher/Das Fliegende Kamel/1-30 Nasreddin Hodscha.m4a" },
    { nr: 31, titel: "Nasreddin Hodscha (CD 2)",              datei: "./buecher/Das Fliegende Kamel/2-01 Nasreddin Hodscha.m4a" },
    { nr: 32, titel: "Parnin Sesi",                           datei: "./buecher/Das Fliegende Kamel/2-02 Parnin Sesi.m4a" },
    { nr: 33, titel: "Uyku Tulumu",                           datei: "./buecher/Das Fliegende Kamel/2-03 Uyku Tulumu.m4a" },
    { nr: 34, titel: "Adil Karar",                            datei: "./buecher/Das Fliegende Kamel/2-04 Adil Karar.m4a" },
    { nr: 35, titel: "Cevizler Ve Karpuzlar",                 datei: "./buecher/Das Fliegende Kamel/2-05 Cevizler Ve Karpuzlar.m4a" },
    { nr: 36, titel: "Uyanik Enayi",                          datei: "./buecher/Das Fliegende Kamel/2-06 Uyanik Enayi.m4a" },
    { nr: 37, titel: "Vaaz",                                  datei: "./buecher/Das Fliegende Kamel/2-07 Vaaz.m4a" },
    { nr: 38, titel: "Ucan Deve",                             datei: "./buecher/Das Fliegende Kamel/2-08 Ucan Deve.m4a" },
    { nr: 39, titel: "Boguln Adamin Kurtulusu",               datei: "./buecher/Das Fliegende Kamel/2-09 Boguln Adamin Kurtulusu.m4a" },
    { nr: 40, titel: "Nasreddin Hoca Akil Stiyor",            datei: "./buecher/Das Fliegende Kamel/2-10 Nasreddin Hoca Akil Stiyor.m4a" },
    { nr: 41, titel: "Esek",                                  datei: "./buecher/Das Fliegende Kamel/2-11 Esek.m4a" },
    { nr: 42, titel: "Tavuk Corbasi",                         datei: "./buecher/Das Fliegende Kamel/2-12 Tavuk Corbasi.m4a" },
    { nr: 43, titel: "Pahali Terzi",                          datei: "./buecher/Das Fliegende Kamel/2-13 Pahali Terzi.m4a" },
    { nr: 44, titel: "Okcu",                                  datei: "./buecher/Das Fliegende Kamel/2-14 Okcu.m4a" },
    { nr: 45, titel: "Nehir Kiyisinda",                       datei: "./buecher/Das Fliegende Kamel/2-15 Nehir Kiyisinda.m4a" },
    { nr: 46, titel: "Sen De Hakhisin",                       datei: "./buecher/Das Fliegende Kamel/2-16 Sen De Hakhisin.m4a" },
    { nr: 47, titel: "Nasreddin Hoca Bahse Girerse",          datei: "./buecher/Das Fliegende Kamel/2-17 Nasreddin Hoca Bahse Girerse.m4a" },
    { nr: 48, titel: "Acikan Cep",                            datei: "./buecher/Das Fliegende Kamel/2-18 Acikan Cep.m4a" },
    { nr: 49, titel: "Telefon",                               datei: "./buecher/Das Fliegende Kamel/2-19 Telefon.m4a" },
    { nr: 50, titel: "Hava Raporu",                           datei: "./buecher/Das Fliegende Kamel/2-20 Hava Raporu.m4a" },
    { nr: 51, titel: "Arabada",                               datei: "./buecher/Das Fliegende Kamel/2-21 Arabada.m4a" },
    { nr: 52, titel: "Mektup",                                datei: "./buecher/Das Fliegende Kamel/2-22 Mektup.m4a" },
    { nr: 53, titel: "Kaz",                                   datei: "./buecher/Das Fliegende Kamel/2-23 Kaz.m4a" },
    { nr: 54, titel: "Yagmur",                                datei: "./buecher/Das Fliegende Kamel/2-24 Yagmur.m4a" },
    { nr: 55, titel: "Uyku Sorunu",                           datei: "./buecher/Das Fliegende Kamel/2-25 Uyku Sorunu.m4a" },
    { nr: 56, titel: "Soguk",                                 datei: "./buecher/Das Fliegende Kamel/2-26 Soguk.m4a" },
    { nr: 57, titel: "Perhiz",                                datei: "./buecher/Das Fliegende Kamel/2-27 Perhiz.m4a" },
    { nr: 58, titel: "Iki Bardak",                            datei: "./buecher/Das Fliegende Kamel/2-28 Iki Bardak.m4a" },
    { nr: 59, titel: "Yaslilik",                              datei: "./buecher/Das Fliegende Kamel/2-29 Yaslilik.m4a" },
    { nr: 60, titel: "Nasreddin Hodscha (CD 2 Ende)",         datei: "./buecher/Das Fliegende Kamel/2-30 Nasreddin Hodscha.m4a" }
  ]
});
